### PR TITLE
Correct navbar on changelog page

### PR DESCRIPTION
**Pull request by vlakoff**
Current navbar is from the documentation bundled with the release,
which has some differences, amongst others the navbar.

### CODE REVIEW

**Review by erikd — APPROVED** [review]

**Comment by erikd** [comment]
Thanks!

**Comment by vlakoff** [comment]
Uh, the commit doesn't appear in the history?

**Comment by erikd** [comment]
It does now. Github is actually only a mirror of the git repo at xiph.org. It taks a bit of time for commits to propagate.

**Comment by vlakoff** [comment]
I just went to the website, and it seems this error is back. Probably reintroduced during the 1.3.3 release.

**Comment by vlakoff** [comment]
"Bump", issue still present ;)

I think that's because the [changelog from the flac release](https://github.com/xiph/flac/blob/master/doc/html/changelog.html) has to be slightly adjusted (as on this PR) when reusing it for the website.

**Pull request merged**
