### PR TITLE
Port FLAC website to Jekyll, support mobile devices

### PR DESCRIPTION
**Pull request by ktmf01**
Furthermore, the comparison page is mostly removed, as it was severly
outdated. It now links to more up-to-date comparisons.

Other (minor) changes:
- links to sourceforge are changed to links to github
- mentions of FLAC Frontend are removed
- made background colors slightly less pronounced
- fix homebrew link
- deduplicate news from homepage
- removed a few links from navbar, to aid mobile navigation
- remove mentions of XiphQt
- remove the 'Ask Apple for FLAC support in iTunes' page and links

### CODE REVIEW

**Comment by ktmf01** [comment]
I've uploaded the result of jekyll generation here, so the impact of this PR can be properly reviewed: http://www.audiograaf.nl/flac-previs/index.html

**Review by rillian — CHANGES_REQUESTED** [review]
Thanks for doing the conversion! Generally looks good.

Can you please port the rss feed as well? I don't mind if the guids all change, but it's getting several thousand hits a day and looks like people are actually using it so it would be nice to continue publishing announcements through that channel.

**Comment by ktmf01** [comment]
Would it be possible to run a plugin for that? There is an [official plugin to generate a feed from posts](https://github.com/jekyll/jekyll-feed). That way we can deduplicate as much as possible.

**Review by rillian — APPROVED** [review]

**Comment by rillian** [comment]
Thanks! Deployed now. Let me know if there are any issues!

**Comment by ktmf01** [comment]
Many thanks! This will make plugging in documents from the flac sources much easier. As you might have seen, I've converted the man page documents to markdown, so the tool documentation on the website can be generated from that starting with the next release. So, on each release, changelog.md, flac.md, metaflac.md and the api documentation can be copied pretty much directly.

**Pull request merged**
